include: package:flutter_lints/flutter.yaml

formatter:
  page_width: 120
  trailing_commas: preserve

linter:
  rules:
    prefer_single_quotes: true
    always_declare_return_types: true
    type_annotate_public_apis: true
    use_key_in_widget_constructors: true
    sort_child_properties_last: true
    avoid_print: true
    sort_constructors_first: true
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    unnecessary_const: true
    prefer_relative_imports: true
